name = "azizati-id"
compatibility_date = "2026-04-24"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "AZIZATI_DB"
database_name = "azizati-id"
database_id = "9546438a-10a5-4aec-b9b4-ea2704ae9e7e"
